/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.arma.Proyectil;
import com.mycompany.servicio.ServicioProyectiles;
import javax.swing.JOptionPane;

/**
 *
 * @author jupaf
 */
public class GUICrearProyectil extends javax.swing.JFrame {
    private ServicioProyectiles servicioProyectiles;
    /**
     * Creates new form GUICrearProyectil
     * @param servicioProyectiles
     */
    public GUICrearProyectil(ServicioProyectiles servicioProyectiles) {
        this.servicioProyectiles = servicioProyectiles;
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFTipo = new javax.swing.JTextField();
        TFVelocidad = new javax.swing.JTextField();
        TFRadio = new javax.swing.JTextField();
        btnCrearProyectil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CrearProyectil");

        jLabel1.setText("Tipo de proyectil");

        jLabel2.setText("Velocidad del proyectil ");

        jLabel3.setText("Radio de explosion ");

        TFTipo.setForeground(new java.awt.Color(0, 0, 0));
        TFTipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TFTipo.setToolTipText("");
        TFTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTipoActionPerformed(evt);
            }
        });

        TFVelocidad.setForeground(new java.awt.Color(0, 0, 0));
        TFVelocidad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TFVelocidad.setToolTipText("");

        TFRadio.setForeground(new java.awt.Color(0, 0, 0));
        TFRadio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TFRadio.setToolTipText("");
        TFRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRadioActionPerformed(evt);
            }
        });

        btnCrearProyectil.setText("Crear Proyectil");
        btnCrearProyectil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProyectilActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TFTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TFVelocidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TFRadio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCrearProyectil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFTipo)
                    .addComponent(TFVelocidad)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(166, 166, 166))
                    .addComponent(TFRadio)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnCrearProyectil)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(TFTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFVelocidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(TFRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearProyectil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRadioActionPerformed

    private void btnCrearProyectilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProyectilActionPerformed
        if (TFTipo.getText().trim().isEmpty() || TFVelocidad.getText().trim().isEmpty() || TFRadio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.", "Información", JOptionPane.HEIGHT);
            return;
        }
        Proyectil pro = new Proyectil((String)TFTipo.getText().trim(),Float.parseFloat(TFVelocidad.getText().trim()),Float.parseFloat(TFRadio.getText().trim()));
        servicioProyectiles.añadirProyectil(pro);
        JOptionPane.showMessageDialog(this, "Exito al crear el proyectil", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCrearProyectilActionPerformed

    private void TFTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTipoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFRadio;
    private javax.swing.JTextField TFTipo;
    private javax.swing.JTextField TFVelocidad;
    private javax.swing.JButton btnCrearProyectil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
