/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.model.Arma;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author jupaf
 */
public class GUIJuego extends javax.swing.JFrame {

    private Arma jugador1;
    private Arma jugador2;

    /**
     * Creates new form GUIJuego
     */
    public GUIJuego(Arma jugador1, Arma jugador2) {
        
        

        // Clonar los objetos para mantener su tipo original
        this.jugador1 = jugador1.clone();
        this.jugador2 = jugador2.clone();

        System.out.println(jugador1.getClass() + "      " + jugador2.getClass());
        initComponents();
        this.setFocusable(true);
        this.requestFocusInWindow();

        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Vida1 = new javax.swing.JLabel();
        Vida2 = new javax.swing.JLabel();
        Recarga1 = new javax.swing.JLabel();
        Recarga2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Interfaz del juego");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton1.setText("Disparar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Disparar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Vida1.setText("Vida");

        Vida2.setText("Vida");

        Recarga1.setFont(new java.awt.Font("Script MT Bold", 2, 35)); // NOI18N

        Recarga2.setFont(new java.awt.Font("Script MT Bold", 2, 35)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Recarga1)
                        .addGap(61, 61, 61)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Recarga2)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vida1)
                    .addComponent(Vida2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Recarga1)
                    .addComponent(Recarga2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jugador2.getVida() <= 0) {
            JOptionPane.showMessageDialog(this, "Ganador jugador 1",
                    "Ganador", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        if (jugador1.getMunicion() == 0) {

            Recarga1.setText("Recargando...");
            Thread t1 = new Thread(new Runnable() {
                public void run() {
                    // code goes here.
                    jugador1.recargar();
                    Recarga1.setText("");
                }
            });
            t1.start();

        } else {

            jugador2 = jugador1.disparar(jugador2);
            if (jugador2.getVida() <= 0) {
                JOptionPane.showMessageDialog(this, "Ganador jugador 1",
                        "Ganador", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            System.out.println("vida: " + jugador2.getVida() + "daño" + jugador1.getDaño());

            Vida2.setText(String.valueOf(jugador2.getVida()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jugador1.getVida() <= 0) {
            JOptionPane.showMessageDialog(this, "Ganador jugador 2",
                    "Ganador", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        if (jugador2.getMunicion() == 0) {
            Recarga2.setText("Recargando...");
            Thread t1 = new Thread(new Runnable() {
                public void run() {
                    // code goes here.
                    jugador2.recargar();
                    Recarga2.setText("");
                }
            });
            t1.start();
        } else {
            jugador1 = jugador2.disparar(jugador1);
            if (jugador1.getVida() <= 0) {
                JOptionPane.showMessageDialog(this, "Ganador jugador 2",
                        "Ganador", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            System.out.println("vida: " + jugador1.getVida() + "daño" + jugador2.getDaño());

            Vida1.setText(String.valueOf(jugador1.getVida()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_A) {
            System.out.println("a");
            jButton1.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_P) {
            System.out.println("p");
            jButton2.doClick();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Recarga1;
    private javax.swing.JLabel Recarga2;
    private javax.swing.JLabel Vida1;
    private javax.swing.JLabel Vida2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
