/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.arma.Proyectil;
import com.mycompany.servicio.ServicioArma;
import com.mycompany.servicio.ServicioProyectiles;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jupaf
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    private ServicioProyectiles servicioProyectiles = new ServicioProyectiles();
    private ServicioArma servicioArma = new ServicioArma();

    public GUIPrincipal() {
        // Eliminar bordes y barra de título

        // Maximizar la ventana
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMenuItemCProyectiles = new javax.swing.JMenuItem();
        jMenuItemListarProyectiles = new javax.swing.JMenuItem();
        jmArma = new javax.swing.JMenu();
        miCrearArma = new javax.swing.JMenuItem();
        miListarArma = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miAcerca = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        JMenuSalir.setText("Salir");
        JMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Proyectiles");

        JMenuItemCProyectiles.setText("Crear");
        JMenuItemCProyectiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCProyectilesActionPerformed(evt);
            }
        });
        jMenu2.add(JMenuItemCProyectiles);

        jMenuItemListarProyectiles.setText("Listar");
        jMenuItemListarProyectiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarProyectilesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemListarProyectiles);

        jMenuBar1.add(jMenu2);

        jmArma.setText("Armas");

        miCrearArma.setText("Crear");
        miCrearArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearArmaActionPerformed(evt);
            }
        });
        jmArma.add(miCrearArma);

        miListarArma.setText("Listar");
        miListarArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarArmaActionPerformed(evt);
            }
        });
        jmArma.add(miListarArma);

        jMenuBar1.add(jmArma);

        jMenu5.setText("Ayuda");

        miAcerca.setText("Acerca de");
        miAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcercaActionPerformed(evt);
            }
        });
        jMenu5.add(miAcerca);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuSalirActionPerformed

    private void JMenuItemCProyectilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCProyectilesActionPerformed
        GUICrearProyectil gui = new GUICrearProyectil(servicioProyectiles);
        gui.setVisible(true);
    }//GEN-LAST:event_JMenuItemCProyectilesActionPerformed

    private void jMenuItemListarProyectilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarProyectilesActionPerformed
        // TODO add your handling code here:
        GUIListarProyectiles gui = new GUIListarProyectiles(servicioProyectiles);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarProyectilesActionPerformed

    private void miAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Autores: Juan Alvarez, Sebastian, Juan Forero", "Acerca de nosotros", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_miAcercaActionPerformed

    private void miCrearArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearArmaActionPerformed
        GUICrearArma gui = new GUICrearArma(servicioArma, servicioProyectiles);
        gui.setVisible(true);
    }//GEN-LAST:event_miCrearArmaActionPerformed

    private void miListarArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarArmaActionPerformed
        GUIListarArmas gui = new GUIListarArmas(servicioArma);
        gui.setVisible(true);
    }//GEN-LAST:event_miListarArmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemCProyectiles;
    private javax.swing.JMenuItem JMenuSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemListarProyectiles;
    private javax.swing.JMenu jmArma;
    private javax.swing.JMenuItem miAcerca;
    private javax.swing.JMenuItem miCrearArma;
    private javax.swing.JMenuItem miListarArma;
    // End of variables declaration//GEN-END:variables
}
